Repository apache/shenyu, pull requests merged in 2021-05, with the labels that each got.

#1383 fix: typo
  README_CN.md
Labels: in: document

#1384 update RedisRateLimiter error log.
  soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java
  soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/executor/RedisRateLimiter.java
Labels: type: refactor

#1382 add query conditions for some pages in Soul-Dashboard.
  soul-admin/src/main/java/org/dromara/soul/admin/controller/PluginController.java
  soul-admin/src/main/java/org/dromara/soul/admin/controller/PluginHandleController.java
  soul-admin/src/main/java/org/dromara/soul/admin/model/query/PluginHandleQuery.java
  soul-admin/src/main/java/org/dromara/soul/admin/model/query/PluginQuery.java
  soul-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
  soul-admin/src/main/resources/mappers/plugin-sqlmap.xml
  soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginControllerTest.java
  soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginHandleControllerTest.java
  soul-admin/src/test/java/org/dromara/soul/admin/service/PluginServiceTest.java
Labels: soul-admin

#1388 Fix init h2 sql
  soul-admin/src/main/resources/META-INF/schema.h2.sql
Labels: type: bug

#1390 #1381 avoid 2.7.5-version conflict
  soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java
Labels: plugin: apache-dubbo

#1406 modify spi
  shenyu-admin/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-metrics/shenyu-metrics-prometheus/src/main/resources/META-INF/shenyu/org.apache.shenyu.metrics.spi.MetricsBootService
  shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.strategy.MatchStrategy
  shenyu-plugin/shenyu-plugin-base/src/test/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.strategy.MatchStrategy
  shenyu-plugin/shenyu-plugin-divide/src/test/resources/META-INF/shenyu/org.apache.shenyu.plugin.divide.balance.LoadBalance
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.ratelimiter.algorithm.RateLimiterAlgorithm
  shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
  shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.HasDefaultSPI
  shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.JdbcSPI
  shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.NoClassMatchSPI
  shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.NoJoinSPI
  shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.NotMatchSPI
Labels: type: refactor, type: spi

#1420 rename soul to shenyu in web (#1394)
  shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ErrorHandlerConfiguration.java
  shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ExcludePathProperties.java
  shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuConfiguration.java
  shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuExtConfiguration.java
  shenyu-web/src/main/java/org/apache/shenyu/web/fallback/DefaultFallbackController.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/AbstractWebFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/ExcludeFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/FileSizeFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/TimeWebFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/WebSocketParamFilter.java
  shenyu-web/src/main/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolver.java
  shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
  shenyu-web/src/test/java/org/apache/shenyu/web/fallback/DefaultFallbackControllerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/filter/FileSizeFilterTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/filter/WebSocketParamFilterTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolverTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/handler/GlobalErrorHandlerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/handler/ShenyuWebHandlerTest.java
Labels: type: refactor

#1421 Add test DataPermissionController in DataPermissionControllerTest
  shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DataPermissionControllerTest.java
  shenyu-bootstrap/pom.xml
Labels: in: test

#1430 fix bug
  shenyu-admin/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-bootstrap/src/main/resources/application-local.yml
  shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.client.api.SoulClientRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
  shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.server.api.SoulServerRegisterRepository
Labels: type: refactor

#1441 Change some names from soul to shenyu (#1394)
  shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/executor/RegisterClientConsumerExecutor.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/validation/AlibabaDubboClientValidator.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
  shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/ShenyuThreadFactoryTest.java
  shenyu-common/src/test/java/org/apache/shenyu/common/utils/GsonUtilsTest.java
  shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegisterTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/AndMatchStrategyTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/OrMatchStrategyTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/handler/PluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/FallbackUtilsTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/MatchStrategyUtilsTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/UriUtilsTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/client/GrpcClientBuilder.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/context/GrpcShenyuContextDecorator.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/reflection/ShenyuGrpcReflectionClient.java
  shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
Labels: type: refactor

#1453 cache dubbo provider version
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/handler/ApacheDubboPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCacheTest.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
Labels: plugin: apache-dubbo, type: refactor

#1450 support custom fallback handler
  shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/SentinelPlugin.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sentinel/src/main/java/org/apache/shenyu/springboot/starter/plugin/sentinel/SentinelPluginConfiguration.java
Labels: plugin: sentinel, type: refactor

#1463 Add hyperlinks to some notes
  script/shenyu_checkstyle.xml
  shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/TokenBucketRateLimiterAlgorithm.java
  shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
  shenyu-spi/src/main/java/org/apache/shenyu/spi/SPI.java
  shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ErrorHandlerConfiguration.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/support/BodyInserterContext.java
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/support/CachedBodyOutputMessage.java
Labels: type: enhancement

#1468 bugfix: fix shenyu-admin-dist start.sh and shenyu-bootstrap-dist star…
  shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh
  shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
Labels: type: build

#1374 Fix the judgment of update flag
  shenyu-admin/src/main/resources/META-INF/schema.h2.sql
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/DataRefreshFactory.java
Labels: type: refactor

#1472 Enhance shenyu-register-client module unit test and add NacosClientRegisterRepository close method to shutdown config and naming service.
  shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
  shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/test/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepositoryTest.java
Labels: client: register, type: refactor

#1479 Enhance shenyu-plugin-dubbo-common module unit test. and remove redundant code.
  shenyu-plugin/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/context/DubboShenyuContextDecorator.java
  shenyu-plugin/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/context/DubboShenyuContextDecoratorTest.java
Labels: in: test

#1445 fix 1439 @ShenyuXXXClient not found
  shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
  shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
  shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
Labels: type: refactor

#1454 fix #1451
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java
Labels: plugin: dubbo, type: refactor

#1480 enhance soul-plugin-base unti test coverage.
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/BaseHandleCacheTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/EmptyMockBaseHandleCache.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtilsTest.java
Labels: in: test

#1483 fix guava cache usage (#1477)
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCacheTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/cache/ApplicationConfigCache.java
Labels: type: refactor

#1484 Enhance shenyu-plugin-alibaba-dubbo module unit test
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPluginTest.java
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCacheTest.java
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
Labels: in: test, plugin: dubbo

#1486 completed the task of issue#1485
  shenyu-web/src/main/java/org/apache/shenyu/web/filter/WebSocketParamFilter.java
Labels: type: refactor

#1482 fix #1478
  shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
Labels: type: refactor

#1487 Optimize getTargetClass method and fix sofa examples
  shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
  shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
  shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
  shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/resources/invoke-server-example.xml
Labels: type: refactor

#1489 Enhance shenyu-register-center module unit test #1457
  pom.xml
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/pom.xml
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java
  shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java
Labels: in: test

#1492 add rpcType param in header
  shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilder.java
Labels: type: refactor

#1493 Add scheduler config
  shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
Labels: type: refactor

#1501 Use SPI refactor PredicateJudge
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/ContainsPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/EqualsPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/GroovyPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/MatchPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactory.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/RegexPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/SpELPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/TimerAfterPredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/TimerBeforePredicateJudge.java
  shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.judge.PredicateJudge
Labels: type: refactor, type: spi

#1505 reload upstream data from db when client register to shenyu-admin
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuClientRegisterServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
Labels: soul-admin, type: refactor

#1510 Refactor code about "async invoke" in dubbo plugin (#1498)
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCache.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/handler/ApacheDubboPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCacheTest.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
Labels: type: refactor

#1511 Add test cases for HeaderParameterData (#1508)
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HeaderParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactoryTest.java
Labels: in: test

#1516 Enhance shenyu-plugin-grpc module unit test.
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/client/ShenyuGrpcClientTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/context/GrpcShenyuContextDecoratorTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/proto/CompleteObserverTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/proto/CompositeStreamObserverTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/proto/DynamicMessageMarshallerTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/proto/MessageWriterTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/proto/MyStreamObserver.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuNameResolverProviderTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuResolverHelperTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuServiceInstanceListsTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuServiceInstanceTest.java
  shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/response/GrpcResponsePluginTest.java
Labels: in: test

#1526 Ipparameter data test
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/IpParameterDataTest.java
Labels: in: test

#1528 1494
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/RewriteHandle.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java
  shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/RewritePluginTest.java
Labels: plugin: rewrite

#1532 Use charset for heath info in HealthFilter
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/filter/HealthFilter.java
Labels: type: refactor

#1534 fix nacos error
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/NacosSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
Labels: type: refactor

#1530 Customized netty tcp config #1529
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java
Labels: type: refactor

#1541 add jwt plugin
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
  shenyu-plugin/pom.xml
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultEnum.java
  shenyu-plugin/shenyu-plugin-jwt/pom.xml
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/config/JwtConfig.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/lambda/ThrowingFunction.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/java/org/apache/shenyu/springboot/starter/plugin/jwt/JwtPluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/resources/META-INF/spring.factories
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/resources/META-INF/spring.provides
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/test/java/org/apache/shenyu/springboot/starter/plugin/jwt/JwtPluginConfigurationTest.java
Labels: plugin: jwt

#1550 cleanup
  shenyu-admin/src/test/java/org/apache/shenyu/admin/config/DataSyncConfigurationTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListenerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosMockConfigService.java
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/resources/application.yml
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/resources/application.yml
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPlugin.java
  shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/ApacheDubboPlugin.java
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultEnum.java
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/WebFluxResultUtils.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/FallbackUtils.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/FallbackUtilsTest.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
  shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java
  shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
  shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/WafPlugin.java
Labels: type: refactor

#1554 add test for ParameterData
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/ParameterDataFactoryTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/PostParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/QueryParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/RequestMethodParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/URIParameterDataTest.java
Labels: in: test

#1558 Fix checked
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/AuthParamData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/SelectorData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/WebsocketData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/RemoteAddressResolver.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/handler/DividePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/WafPlugin.java
Labels: type: refactor
