Repository apache/shenyu, pull requests merged in 2021-07, with the labels that each got.

#1686 [ISSUE #1679] Add category and sort for plugin list.
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/PluginDO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/PluginVO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
  shenyu-admin/src/main/resources/META-INF/schema.h2.sql
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
  shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginControllerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketDataChangedListenerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ShenyuClientRegisterServiceTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SyncDataServiceTest.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
  shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-monitor/src/test/java/org/apache/shenyu/plugin/monitor/handler/MonitorPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
  shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-tars/src/test/java/org/apache/shenyu/plugin/tars/handler/TarsPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/WafPluginTest.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandlerTest.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java
  shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/handler/PluginDataHandlerTest.java
  shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/handler/WebsocketDataHandlerTest.java
Labels: admin

#1694 Removed unnecessary constants
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
Labels: type: refactor

#1697 [ISSUE #1292] add ModifyResponsePlugin
  shenyu-admin/src/main/resources/META-INF/schema.h2.sql
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-bootstrap/pom.xml
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ModifyResponseRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
  shenyu-plugin/pom.xml
  shenyu-plugin/shenyu-plugin-modify-response/pom.xml
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/ModifyResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/cache/ModifyResponseRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/handler/ModifyResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/main/java/org/apache/shenyu/springboot/starter/plugin/modifyresponse/ModifyResponsePluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/main/resources/META-INF/spring.factories
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/main/resources/META-INF/spring.provides
Labels: plugin: modify-response

#1702 [refactor #1703] refactor code
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/balance/spi/AbstractLoadBalance.java
Labels: type: refactor

#1710 [ISSUE #1709] Add test case for shenyu-admin module
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdClientTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataInitTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListenerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataInitTest.java
Labels: in: test

#1725 [ISSUE #1700] Remove distributionManagement and sonatype plugin
  pom.xml
Labels: type: release

#1722 [ISSUE #1721] Add test case for param-mapping and remove the cache module of plugins
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/BaseHandleCache.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/RuleHandleCache.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/BeanHolder.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/EmptyMockRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/RuleHandleCacheTest.java
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/cache/ContextPathRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/handler/ContextPathPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-context-path/src/test/java/org/apache/shenyu/plugin/context/path/ContextPathPluginTest.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/cache/UpstreamCacheManager.java
  shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java
  shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/cache/HystrixRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/handler/HystrixPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-hystrix/src/test/java/org/apache/shenyu/plugin/hystrix/HystrixPluginTest.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/ModifyResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/cache/ModifyResponseRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/response/handler/ModifyResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-param-mapping/pom.xml
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/ParamMappingPlugin.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/cache/ParamMappingRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/handler/ParamMappingPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/FormDataOperator.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperator.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/Operator.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/OperatorFactory.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/ParamMappingPluginTest.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/handler/ParamMappingPluginDataTest.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/DefaultOperatorTest.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/FormDataOperatorTest.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperatorTest.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPlugin.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPluginTest.java
  shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/RedirectPlugin.java
  shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/cache/RedirectRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/handler/RedirectPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-redirect/src/test/java/org/apache/shenyu/plugin/redirect/RedirectPluginTest.java
  shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java
  shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandler.java
  shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/RequestPluginTest.java
  shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandlerTest.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/cache/Resilience4jRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandler.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPluginTest.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/cache/RewriteRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/RewritePluginTest.java
  shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/cache/SpringCloudRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/cache/SpringCloudSelectorHandleCache.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/WafPlugin.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/cache/WafRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/WafPluginTest.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandlerTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-param-mapping/src/main/java/org/apache/shenyu/springboot/starter/plugin/param/mapping/ParamMappingPluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-param-mapping/src/test/java/org/apache/shenyu/springboot/starter/plugin/param/mapping/ParamMappingPluginConfigurationTest.java
Labels: in: test

#1734 [ISSUE #1717]Fix bug(#1717), when sync data by zookeeper, it will throw ClassCastException
  shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java
Labels: data-sync: zookeeper, type: bug

#1732 Use h2 for integrated test
  .github/workflows/create-pr-4-dashboard.yml
  shenyu-admin/src/main/resources/application.yml
  shenyu-dist/shenyu-admin-dist/entrypoint.sh
  shenyu-examples/shenyu-examples-http/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-http/admin-config/schema.sql
  shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
Labels: integration-test, type: build

#1738 [ISSUE #1700] Rename CHANGELOG.md to RELEASE-NOTES.md
  RELEASE-NOTES.md
Labels: type: release

#1739 [ISSUE #1700] Add mvnw license
  LICENSE
Labels: type: release

#1726 [ISSUE #1714] Add test case for shenyu-plugin-sign.
  shenyu-integrated-test/shenyu-integrated-test-http/admin-config/schema.sql
  shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/SignTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/helper/HttpHelper.java
Labels: integration-test

#1705 [ISSUE #1704] add test case for shenyu-plugin-modify-response
  shenyu-admin/src/main/resources/META-INF/schema.h2.sql
  shenyu-admin/src/main/resources/META-INF/schema.sql
  shenyu-bootstrap/pom.xml
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/cache/ModifyResponseRuleHandleCache.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/handler/ModifyResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePluginTest.java
  shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/cache/ModifyResponseRuleHandleCacheTest.java
  shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/handler/ModifyResponsePluginDataHandlerTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/main/java/org/apache/shenyu/springboot/starter/plugin/modify/response/ModifyResponsePluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/main/resources/META-INF/spring.factories
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-modify-response/src/test/java/org/apache/shenyu/springboot/starter/plugin/modify/response/ModifyResponsePluginConfigurationTest.java
Labels: in: test

#1754 polishcode
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
Labels: type: refactor

#1765 polish health check for integrated-test
  .github/workflows/integrated-test-http.yml
  shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-http/script/healthcheck.sh
  shenyu-integrated-test/shenyu-integrated-test-http/script/services.list
Labels: integration-test

#1769 [ISSUE #1700] Change the profile name from dist to release
  .github/workflows/integrated-test-http.yml
  shenyu-dist/README.md
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-integrated-test/README.md
Labels: type: release

#1773 [ISSUE #1700] Add shenyu-src-dist
  DISCLAIMER
  shenyu-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
  shenyu-dist/shenyu-src-dist/src/main/assembly/source.xml
Labels: type: release

#1771 [ISSUE #1770] Solve the problem of duplicate URL-encoding
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
Labels: plugin: http-client

#1774 [ISSUE #1700] Refine license headers
  lombok.config
  pom.xml
  shenyu-admin/src/main/resources/static/favicon.ico
  shenyu-admin/src/main/resources/static/favicon.png
  shenyu-admin/src/main/resources/static/index.40aac744.js
  shenyu-admin/src/main/resources/static/index.6e738f45.css
  shenyu-admin/src/main/resources/static/index.html
  shenyu-examples/shenyu-examples-tars/src/main/resources/ShenyuExampleServer.ShenyuExampleApp.config.conf
  shenyu-examples/shenyu-examples-tars/src/main/resources/test.tars
Labels: type: release

#1783 [ISSUE# 1700] Update release notes
  RELEASE-NOTES.md
Labels: type: release

#1784 [ISSUE #1700] Add consul license
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/licenses/LICENSE-consul.txt
  shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
  shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/licenses/LICENSE-consul.txt
Labels: type: release

#1786 [Bug-Fix #1778] fix uri encode
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
Labels: type: bug

#1787 Update release notes
  RELEASE-NOTES.md
Labels: type: release

#1788 [ISSUE #1700] Change the scm address to https
  pom.xml
Labels: type: release

#1791 [ISSUE #1700] Refine release config
  pom.xml
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
Labels: type: release

#1792 [ISSUE #1700] Refine release config
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
Labels: type: release

#1799 refine release config
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
Labels: type: release

#1810 Simplify some code
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/handler/ContextPathPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/handler/HystrixPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/handler/ModifyResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/handler/RedirectPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandler.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandler.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandler.java
Labels: type: refactor

#1666 [ISSUE #1665] Improve health check for divide plugin
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/DivideUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/healthcheck/HealthCheckTask.java
  shenyu-common/src/main/java/org/apache/shenyu/common/healthcheck/UpstreamWithSelectorId.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/cache/UpstreamCacheManager.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/DividePluginTest.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/cache/UpstreamCacheManagerTest.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/handler/DividePluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/websocket/WebSocketPluginTest.java
Labels: status: discuss, status: pending

#1816 Fix BUG: Cannot startup shenyu-admin docker on Windows
  shenyu-dist/shenyu-admin-dist/entrypoint.sh
Labels: integration-test, type: build

#1815 fix: NPE when refreshURIService
  shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java
Labels: type: refactor

#1819 [ISSUE #1817] Change the parent project of the shenyu-integrated-test to shenyu
  shenyu-integrated-test/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-http/src/main/java/org/apache/shenyu/integratedtest/App.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/AbstractTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/AppTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/HelloWorldTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/HttpRateLimitTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/SignTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/dto/AdminResponse.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/helper/HttpHelper.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/package-info.java
Labels: integration-test

#1821 update UpstreamCheckService
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/ZombieUpstream.java
Labels: type: refactor

#1836 [ISSUE #1700] Fix license issues
  pom.xml
  shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/ThreadLocalUtilTest.java
  shenyu-dist/shenyu-src-dist/src/main/assembly/source.xml
Labels: type: release

#1843 [ISSUE #1841] remove code that cause `mvn install` command execution to fail
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
Labels: in: test
