Repository apache/shenyu, pull requests merged in 2021-11, with the labels that each got.

#2289 [type:refactor] optimize register properties config.
  shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/config/ShenyuClientConfig.java
  shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/config/ShenyuRegisterCenterConfig.java
Labels: type: refactor

#2290 refine dependencies
  shenyu-admin/pom.xml
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/licenses/ui-licenses/LICENSE-postgresql.txt
Labels: type: dependencies

#2295 [type: refactor] fix uri plugin bug.
  shenyu-plugin/shenyu-plugin-uri/src/main/java/org/apache/shenyu/plugin/uri/URIPlugin.java
Labels: type: bug, type: refactor

#2299 [type: bug] fix dubbo multiSelectorHandle duplicate plugin-handle id from 111 to 123.
  script/2.4.1-upgrade-2.4.2.sql
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
  shenyu-admin/src/main/resources/sql-script/pg/schema.sql
Labels: admin, type: refactor

#2300 [refactor: readme] add quick start to readme
  README.md
  README_CN.md
Labels: type: refactor

#2298 [ISSUE #1978] add agent class loader
  shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/ShenyuAgentBootstrap.java
  shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/classloader/AgentClassLoader.java
  shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/exception/AgentBootstrapFailException.java
Labels: feature: agent

#2301 [type: refactor] remove gzip when the request headers exist, to fix modifyResponse Plugin and other exchange mutate plugin.
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/ResponsePlugin.java
Labels: type: refactor

#2302 [type: bug] fix 2225, optimize client response builder.
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ClientResponseUtils.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/decorator/ResponseDecorator.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
Labels: type: refactor

#2305 [ISSUE #2275]Fix register error by nacos
  shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java
Labels: client: reigster-nacos

#2304 [type:refactor] optimize response & cryptor.
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ResponseUtils.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/decorator/CryptorRequestDecorator.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/decorator/CryptorResponseDecorator.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
  shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePluginTest.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
Labels: type: refactor

#2309 [type: refactor] support modify rpc caller response like dubbo.
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ModifyResponseRuleHandle.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ResponseUtils.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePluginTest.java
Labels: type: refactor, plugin: modify-response

#2273 [Volunteer] <Support real async in dubbo request> #2272
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
Labels: plugin: dubbo, type: refactor

#2323 Eliminate the yellow code prompt
  shenyu-admin/src/test/java/org/apache/shenyu/admin/config/NacosConfigurationTest.java
Labels: type: refactor, in: test

#2320 [type: refator] optimize admin db operation.
  shenyu-admin/src/main/java/org/apache/shenyu/admin/config/ShenyuAdminConfiguration.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AppAuthMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AuthParamMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AuthPathMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PermissionMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
  shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/auth-param-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/auth-path-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/permission-sqlmap.xml
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/AppAuthServiceTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PermissionServiceTest.java
Labels: admin, type: refactor

#2318 [type:feature] Support sent in dubbo.
  shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
  shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
Labels: plugin: dubbo, type: refactor

#2326 [type:feature]replace maxCount with Constants.CACHE_MAX_COUNT
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/cache/ApplicationConfigCache.java
Labels: type: refactor

#2329 [type: refactor]refactor and clean code to ModifyResponsePlugin
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/cache/ModifyResponseCommonHandleCache.java
  shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/handler/ModifyResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/cache/ModifyResponseCommonHandleCacheTest.java
Labels: type: refactor, plugin: modify-response

#2327 [type: refactor] optimize admin plugin delete.
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginHandleMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleConditionMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorConditionMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ResourceService.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
  shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/selector-condition-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java
Labels: admin, type: refactor

#2335 #2308, update dockerfile for admin
  shenyu-dist/shenyu-admin-dist/Dockerfile
Labels: type: bug, admin, type: build

#2319 [ISSUE #2009] Enhance the ability of jwt plugin
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
  shenyu-admin/src/main/resources/sql-script/pg/schema.sql
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/JwtRuleHandle.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/JwtPluginTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/config/JwtConfig.java
  shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandler.java
Labels: type: refactor, plugin: jwt

#2340 refactor shenyu-data-sync-center: code polish.
  shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdClient.java
  shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/AbstractDataRefresh.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
  shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
Labels: type: refactor

#2333 [type: refactor] optimize dubbo plugin.
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/decorator/CryptorResponseDecorator.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRequestPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/CryptorStrategyFactory.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/JsonUtil.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPlugin.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaAbstractDubboPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboGrayLoadBalance.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyService.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriber.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCacheTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/ApacheDubboPlugin.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/handler/ApacheAbstractDubboPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboGrayLoadBalance.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCacheTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/handler/ApacheAbstractDubboPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/pom.xml
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPlugin.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboParam.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/handler/AbstractDubboPluginDataHandler.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo/shenyu-spring-boot-starter-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/springboot/starter/plugin/alibaba/dubbo/AlibabaDubboPluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo/shenyu-spring-boot-starter-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/springboot/starter/plugin/alibaba/dubbo/AlibabaDubboPluginConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo/shenyu-spring-boot-starter-plugin-apache-dubbo/src/main/java/org/apache/shenyu/springboot/starter/plugin/apache/dubbo/ApacheDubboPluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo/shenyu-spring-boot-starter-plugin-apache-dubbo/src/test/java/org/apache/shenyu/springboot/starter/plugin/apache/dubbo/ApacheDubboPluginConfigurationTest.java
Labels: plugin: dubbo, type: refactor

#2343 [ISSUE #2339] springCloud router choose error
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/src/main/java/org/apache/shenyu/springboot/starter/plugin/springcloud/SpringCloudPluginConfiguration.java
Labels: type: bug, plugin: spring-cloud

#2344 change getting started link in readme.txt
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/README.txt
  shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/README.txt
Labels: type: build

#2349 refactor shenyu-admin: code polish.
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/EnumServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RoleServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuDictServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/bean/StatelessAuthFilter.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroRealm.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShenyuResultMessage.java
Labels: admin, type: refactor

#2354 fix dist: the static file parammapping rule handle
  shenyu-admin/src/main/resources/static/index.298ebb95.css
  shenyu-admin/src/main/resources/static/index.3c0609d9.js
  shenyu-admin/src/main/resources/static/index.52878f81.js
  shenyu-admin/src/main/resources/static/index.html
Labels: admin

#2355 fix some yellow alert in shenyu-admin module
  shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataInit.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/converter/SelectorHandleConverterFactor.java
Labels: type: refactor

#2359 [ISSUE #2296] Enhanced integration test of RateLimiter plugin
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java
Labels: integration-test

#2362 [type: refactor] `CryptorRuleHandler` implements `RuleHandle`
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java
Labels: type: refactor

#2363 [Integrated-Test] Init combination integrated test
  .github/workflows/integrated-test.yml
  shenyu-integrated-test/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-combination/Dockerfile
  shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-combination/script/healthcheck.sh
  shenyu-integrated-test/shenyu-integrated-test-combination/script/services.list
  shenyu-integrated-test/shenyu-integrated-test-combination/src/main/java/org/apache/shenyu/integrated/test/combination/CombinationIntegratedBootstrap.java
  shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application-local.yml
  shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application.yml
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java
Labels: integration-test

#2332 [ISSUE #2331] change shenyu-admin image version to latest
  pom.xml
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-examples/pom.xml
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
  shenyu-examples/shenyu-examples-eureka/pom.xml
  shenyu-examples/shenyu-examples-grpc/pom.xml
  shenyu-examples/shenyu-examples-http/pom.xml
  shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml
  shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml
  shenyu-examples/shenyu-examples-websocket/pom.xml
  shenyu-integrated-test/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-grpc/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-motan/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-sofa/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-spring-cloud/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-websocket/docker-compose.yml
  shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/docker-compose.yml
  shenyu-integrated-test/shenyu-integration-test-apache-dubbo/docker-compose.yml
Labels: integration-test

#2369 [ISSUE #2366] remove warning codes in shenyu-disruptor module
  shenyu-disruptor/pom.xml
  shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/DisruptorProviderManage.java
  shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/consumer/QueueConsumer.java
  shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/provider/DisruptorProvider.java
Labels: type: refactor, code: clean

#2374 [ISSUE #2373] Remove warning code in shenyu-sync-data-center
  shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataServiceTest.java
  shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandlerTest.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/AppAuthDataRefreshTest.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/RuleDataRefreshTest.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/SelectorDataRefreshTest.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/NacosSyncDataServiceTest.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/config/NacosACMConfigTest.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/config/NacosConfigTest.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandlerTest.java
  shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosMockConfigService.java
Labels: type: refactor, code: clean

#2380 [ISSUE #2377] clean up optimize [shenyu-loadbalancer]
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTask.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamWithSelectorId.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/AbstractLoadBalancer.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalancer.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalancer.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java
Labels: type: refactor, code: clean

#2382 [ISSUE #2368] Remove warning code in shenyu-SPI
  shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionFactory.java
  shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
  shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java
  shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/JdbcSPI.java
Labels: type: refactor, code: clean

#2372 Refactor class name
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/Application.java
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/MultiParamServiceImpl.java
  shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/TestServiceImpl.java
Labels: type: refactor, in: example

#2383 [ISSUE #2373] Remove warning code of HttpSyncDataService.java
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
Labels: type: refactor, code: clean

#2384 [ISSUE #2366] clean up optimize [shenyu-loadbalancer] test code.
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/factory/LoadBalancerFactoryTest.java
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalanceTest.java
Labels: type: refactor, in: test, code: clean

#2392 [ISSUE #2370] remove warning code in shenyu-plugin-api and shenyu-plugin-base
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultWrap.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/support/BodyInserterContext.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/BeanHolder.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/BaseDataCacheTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/CommonHandleCacheTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/CookieParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HeaderParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HostParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/IpParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/ParameterDataFactoryTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/PostParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/QueryParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/RequestMethodParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/URIParameterDataTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/handler/PluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtilsTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/HostAddressUtilsTest.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/UriUtilsTest.java
Labels: type: refactor, code: clean

#2391 [type: bug] fix zk sync error handling event bug.
  shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
Labels: type: bug, type: refactor

#2385 [issue #2370]Remove warning code in [shenyu-plugin-request] module
  shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java
  shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandler.java
  shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/RequestPluginTest.java
Labels: type: refactor, code: clean

#2387 [type:refactor] refactor checkParam
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/JsonUtil.java
Labels: type: refactor

#2395 [ISSUE #2366] <Remove warning code in shenyu-metrics>
  shenyu-metrics/shenyu-metrics-facade/src/main/java/org/apache/shenyu/metrics/facade/MetricsTrackerFacade.java
  shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/collector/BuildInfoCollector.java
  shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootService.java
  shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/config/MetricsConfig.java
Labels: type: refactor, code: clean

#2396 [type:refactor]refactor shenyu-plugin-grpc: code polish.
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/GrpcPlugin.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/client/ShenyuGrpcClient.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/SubChannels.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/picker/AbstractReadyPicker.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/proto/CompleteObserver.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuNameResolver.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuServiceInstance.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuServiceInstanceLists.java
Labels: type: refactor, plugin: grpc

#2393 [Task] add the example and integrated-test modules to parent pom
  .github/workflows/integrated-test.yml
  pom.xml
  shenyu-integrated-test/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-grpc/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-motan/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-sofa/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-websocket/pom.xml
  shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/pom.xml
  shenyu-integrated-test/shenyu-integration-test-apache-dubbo/pom.xml
Labels: type: build

#2397 [ISSUE #2370] <Remove warning code in shenyu-plugin-global、shenyu-spi>
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
  shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/cache/MetaDataCache.java
  shenyu-spi/src/main/java/org/apache/shenyu/spi/SpiExtensionFactory.java
Labels: type: refactor

#2398 [issue #2370] remove warning code in shenyu-plugin-sign and shenyu-plugin-rewrite
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
Labels: type: refactor, code: clean

#2401 [ISSUE #2370] clean up optimize [shenyu-plugin-resilience4j] and [shenyu-plugin-response].
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutor.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutor.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/ResponsePlugin.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/MessageWriter.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriter.java
  shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
Labels: type: refactor, code: clean

#2407 [ISSUE 2071] feat connect
  shenyu-protocol/shenyu-protocol-mqtt/pom.xml
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/AbstractMessageType.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttEnv.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttFactory.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttServerConfiguration.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/ChannelRepository.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/SimpleChannelRepository.java
  shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/utils/EncryptUtil.java
Labels: type: new feature, plugin: mqtt

#2406 [ISSUE #2390]fix bug start.sh do not work
  shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.bat
  shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh
  shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.bat
  shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
Labels: type: build

#2410 [issue #2370]Remove warning code in [shenyu-plugin-resilience4j] #2399
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/build/Resilience4JBuilder.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/conf/Resilience4JConf.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutor.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandler.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutorTest.java
  shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutorTest.java
Labels: type: refactor, plugin: resilience4j, code: clean

#2411 [type: refactor] fix unit test fail
  shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java
Labels: type: refactor, in: test

#2414 [issue #2370]Remove warning code in [shenyu-plugin-context-path]
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
Labels: type: refactor, plugin: context-path, code: clean

#2415 [type:bug] ShiroProperties.getWhiteList() is null
  .github/workflows/ci.yml
  shenyu-admin/pom.xml
  shenyu-bootstrap/pom.xml
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
Labels: type: bug, type: build

#2429 [ISSUE #2365] Add integrated test for combination of dubbo and request plugins
  shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
  shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RpcAndRequestPluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
Labels: integration-test

#2422 [issue #2421]Sometimes duplicate hosts appear in the spring cloud plugin handler when register service
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterGrpcServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterTarsServiceImpl.java
Labels: type: bug, admin

#2428 [type: refactor] optimize data event source to filter null data.
  shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/DataChangedEvent.java
Labels: type: refactor

#2430 [type: refactor] support like field query.
  shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml
Labels: admin, type: refactor

#2399 [issue #2366]Remove warning code in [shenyu-examples]
  shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/controller/GrpcTestController.java
  shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/echo/EchoServiceImpl.java
  shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/stream/StreamServiceImpl.java
  shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java
  shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaMultiParamServiceImpl.java
  shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaSingleParamServiceImpl.java
  shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/controller/OrderController.java
  shenyu-examples/shenyu-examples-websocket/src/main/java/org/apache/shenyu/examples/websocket/handler/EchoHandler.java
Labels: in: example, code: clean

#2419 [issue #2366]Remove warning code in [shenyu-spring-boot-starter-client]
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-alibaba-dubbo/src/test/java/org/apache/shenyu/springboot/starter/client/alibaba/dubbo/ShenyuAlibabaDubboClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-alibaba-dubbo/src/test/resources/application.properties
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-apache-dubbo/src/test/java/org/apache/shenyu/springboot/starter/client/apache/dubbo/ShenyuApacheDubboClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-apache-dubbo/src/test/resources/application.properties
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-common/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-common/src/test/java/org/apache/shenyu/springboot/starter/client/common/config/ShenyuClientCommonBeanConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/test/java/org/apache/dromara/springboot/starter/client/grpc/ShenyuGrpcClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/test/java/org/apache/dromara/springboot/starter/client/grpc/server/ShenyuGrpcServerBuilderTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-motan/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-motan/src/test/java/org/apache/shenyu/springboot/starter/client/motan/ShenyuMotanClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-sofa/src/main/java/org/apache/shenyu/springboot/starter/client/sofa/ShenyuSofaClientConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-sofa/src/test/java/org/apache/shenyu/springboot/starter/client/sofa/ShenyuSofaClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/test/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springmvc/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springmvc/src/test/java/org/apache/shenyu/springboot/starter/client/springmvc/ShenyuSpringMvcClientConfigurationTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-tars/src/test/java/org/apache/shenyu/springboot/starter/client/tars/ShenyuTarsClientConfigurationTest.java
Labels: in: test, code: clean

#2423 [issue #2366]Remove warning code in [shenyu-web]
  shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalMetadataControllerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/filter/ExcludeFilterTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/filter/FileSizeFilterTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolverTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/handler/GlobalErrorHandlerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/handler/ShenyuWebHandlerTest.java
Labels: type: refactor, in: test

#2431 [type: fixed] Illegal base64 character 3c
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RpcAndRequestPluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/CryptorStrategy.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/CryptorStrategyFactory.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/RsaStrategy.java
Labels: type: bug, type: refactor, plugin: cryptor

#2433 [type: refactor] Remove the duplicate comments of the websocketcollector method
  shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java
Labels: type: refactor

#2435 Update SECURITY.md
  SECURITY.md
Labels: type: build, type: community

#2436 [type: refactor] ExcludeOperatorJudge
  shenyu-common/src/test/java/org/apache/shenyu/common/utils/PathMatchUtilsTest.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/ExcludeOperatorJudge.java
Labels: type: refactor

#2440 [type:refactor] rateLimiterAlgorithm use lua script not thredsafe when init the script
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/AbstractRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/LeakyBucketRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/RateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/SlidingWindowRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/TokenBucketRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/algorithm/AbstractRateLimiterAlgorithmTest.java
Labels: type: refactor, plugin: ratelimiter

#2444 [type: refactor] refactor some warning code
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/AbstractRateLimiterAlgorithm.java
  shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
  shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepository.java
Labels: type: refactor

#2445 [ISSUE #2443] Improve the stability of Ratelimiter plugin integration test
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java
Labels: integration-test

#2448 [type: refactor] refactor boostrap pom
  shenyu-bootstrap/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-oauth2/pom.xml
Labels: type: build, type: refactor

#2457 [ISSUE #2456] Fix using etcd cluster to sync data init failed
  shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java
  shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/main/java/org/apache/shenyu/register/server/etcd/client/EtcdClient.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/java/org/apache/shenyu/springboot/sync/data/etcd/EtcdSyncDataConfiguration.java
Labels: type: bug, data-sync: etcd

#2454 [ISSUE #2236] Add unit test for URIPlugin.
  shenyu-plugin/shenyu-plugin-uri/src/test/java/org/apache/shenyu/plugin/uri/URIPluginTest.java
Labels: in: test

#2458 refactor bootstrap: Use the annotation @ConfigurationProperties instead of the @Value in NettyTcpConfig
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java
  shenyu-bootstrap/src/main/resources/application-local.yml
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/NettyTcpConfig.java
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/ShenyuNettyWebServerFactory.java
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/resources/application-local.yml
Labels: type: refactor

#2460 [type: refactor] fix boostrap config bug
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java
Labels: type: refactor

#2464 [type: refactor] fix shenyu-integrated-test: fix NettyTcpConfig bug
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/NettyTcpConfig.java
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/ShenyuNettyWebServerFactory.java
Labels: type: refactor, integration-test

#2455 [ISSUE #2361] add docker-compose
  shenyu-dist/pom.xml
  shenyu-dist/shenyu-docker-compose-dist/pom.xml
  shenyu-dist/shenyu-docker-compose-dist/src/main/assembly/source.xml
  shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-cryptor/src/main/java/org/apache/shenyu/springboot/starter/plugin/cryptor/CryptorPluginConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-cryptor/src/test/java/org/apache/shenyu/springboot/starter/plugin/cryptor/CryptorPluginConfigurationTest.java
Labels: type: build

#2446 [ISSUE #2370]【Code Clean】Remove warning codes in [shenyu-plugin-sofa] module
  shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveService.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveServiceImpl.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyService.java
  shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/param/SofaBodyParamResolveServiceTest.java
  shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyServiceTest.java
Labels: type: refactor, code: clean

#2470 [ISSUE #2465]clean waring code in module shenyu-plugin-oauth2
  shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/OAuth2Plugin.java
  shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/filter/OAuth2PreFilter.java
Labels: type: refactor, code: clean

#2475 [ISSUE #2468] clean warning codes in module shenyu-plugin-ratelimiter
  shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandlerTest.java
Labels: type: refactor, code: clean

#2461 [ISSUE #2144] Add unit test for ShenyuClientRegisterTarsServiceImpl
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterTarsServiceImplTest.java
Labels: in: test

#2472 [ISSUE #2139] Add unit test for ShenyuClientRegisterGrpcServiceImpl
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterGrpcServiceImplTest.java
Labels: in: test

#2478 [ISSUE #2476] When the project is started, the ZK node cannot be found exception
  shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java
Labels: type: refactor

#2466 [type:feature] optimeze sql file for plugin-handle,shenyu-dict
  script/2.4.1-upgrade-2.4.2.sql
  shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/LocalDataSourceLoader.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/BaseTrigger.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/PluginHandleH2Trigger.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShenyuDictH2Trigger.java
  shenyu-admin/src/main/resources/application.yml
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
  shenyu-admin/src/main/resources/sql-script/pg/schema.sql
Labels: admin, type: refactor

#2483 [type: refactor] optimize plugin skip.
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/ShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
  shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPlugin.java
  shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/GrpcPlugin.java
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
  shenyu-plugin/shenyu-plugin-logging/src/main/java/org/apache/shenyu/plugin/logging/LoggingPlugin.java
  shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/MotanPlugin.java
  shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/OAuth2Plugin.java
  shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/ParamMappingPlugin.java
  shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java
  shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/SofaPlugin.java
  shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java
  shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/TarsPlugin.java
  shenyu-plugin/shenyu-plugin-uri/src/main/java/org/apache/shenyu/plugin/uri/URIPlugin.java
  shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java
Labels: type: refactor

#2485 [ISSUE #2370]【Code Clean】Remove warning codes in [shenyu-plugin-monitor] module
  shenyu-plugin/shenyu-plugin-monitor/src/test/java/org/apache/shenyu/plugin/monitor/handler/MonitorPluginDataHandlerTest.java
Labels: type: refactor, in: test

#2489 [type: refactor] optimize logo for duplicate logo print.
  shenyu-web/src/main/java/org/apache/shenyu/web/logo/ShenyuLogo.java
Labels: type: refactor

#2490 [ISSUE #2450] Add unit test for register instance by etcd
  shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/test/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepositoryTest.java
Labels: in: test

#2488 [type: refactor] refactor netty configuration.
  shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
  shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/ShenyuNettyWebServerFactory.java
  shenyu-integrated-test/shenyu-integrated-test-motan/pom.xml
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/NettyTcpProperties.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfiguration.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfigurationTest.java
Labels: type: refactor
