Repository apache/shenyu, pull requests merged in 2023-03, with the labels that each got.

#4417 [type:feat] add L1 cache and trie as L2 cache
  shenyu-bootstrap/src/main/resources/application.yml
  shenyu-common/src/main/java/org/apache/shenyu/common/cache/WindowTinyLFUMap.java
  shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/AbstractShenyuPluginTest.java
  shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
Labels: type: refactor

#4418 [ISSUE #4395] Add mapType to cryptor request and response plugin
  db/init/mysql/schema.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql
  db/upgrade/2.5.1-upgrade-2.6.0-oracle.sql
  db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RequestAndResponsePluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorResponsePluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-websocket/src/test/java/org/apache/shenyu/integrated/test/websocket/UploadControllerTest.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/MapTypeEnum.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
  shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPluginTest.java
Labels: type: new feature, plugin: cryptor

#4439 Dubbo cache bugs
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
Labels: type: bug, plugin: dubbo

#4435 [ISSUE #4395] cryptor plugin support multi fieldNames.
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/AbstractCryptorPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRequestPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorResponsePluginDataHandler.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/plugin/AbstractCryptorPlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/plugin/CryptorRequestPlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/plugin/CryptorResponsePlugin.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/strategy/MapTypeEnum.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
  shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/JsonUtil.java
  shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/plugin/CryptorRequestPluginTest.java
  shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/plugin/CryptorResponsePluginTest.java
  shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-cryptor/src/main/java/org/apache/shenyu/springboot/starter/plugin/cryptor/CryptorPluginConfiguration.java
Labels: type: new feature, plugin: cryptor

#4442 Optimize code for shenyu-admin
  shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketConfigurator.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShenyuDictH2Trigger.java
  shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/client/ClickHouseLogCollectClient.java
Labels: admin, type: refactor

#4416 [TASK] save plugin jar to db
  db/init/mysql/schema.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql
  db/upgrade/2.5.1-upgrade-2.6.0-oracle.sql
  db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
  pom.xml
  shenyu-admin/src/http/http-debug-plugin-controller-api.http
  shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/PluginDO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
  shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginControllerTest.java
  shenyu-common/pom.xml
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/JarDependencyUtils.java
  shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
  shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/MqttPluginTest.java
  shenyu-plugin/shenyu-plugin-brpc/src/test/java/org/apache/shenyu/plugin/brpc/handler/BrpcPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-casdoor/src/test/java/org/apache/shenyu/plugin/casdoor/CasdoorPluginTest.java
  shenyu-plugin/shenyu-plugin-casdoor/src/test/java/org/apache/shenyu/plugin/casdoor/handle/CasdoorPluginDateHandlerTest.java
  shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
  shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-mqtt/src/test/java/org/apache/shenyu/plugin/mqtt/handler/MqttPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-tars/src/test/java/org/apache/shenyu/plugin/tars/handler/TarsPluginDataHandlerTest.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/WafPluginTest.java
  shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandlerTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java
Labels: feature: plugin, admin

#4444 [type:refactor] refactor trie code
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieRuleListener.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieTest.java
  shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
Labels: type: refactor

#4425 [ISSUE #4381] Fix missing HOST header delete operation
  shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java
Labels: type: bug, type: refactor

#4252 Fixed Possible Order dependent Test Problem
  shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListenerTest.java
Labels: in: test

#4430 [ISSUE #4298] zombie -> pass update PENDING_SYNC
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
Labels: type: refactor

#4451 [ISSUE #4431] add p2cLoadBalancer
  db/init/mysql/schema.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-common/src/main/java/org/apache/shenyu/common/enums/LoadBalanceEnum.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/P2cLoadBalancer.java
  shenyu-loadbalancer/src/main/resources/META-INF/shenyu/org.apache.shenyu.loadbalancer.spi.LoadBalancer
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/P2cLoadBalancerTest.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/DividePluginTest.java
Labels: type: new feature

#4462 Optimize code for shenyu-client
  shenyu-client/shenyu-client-brpc/src/main/java/org/apache/shenyu/client/brpc/BrpcContextRefreshedEventListener.java
  shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java
  shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/executor/RegisterClientConsumerExecutor.java
  shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonForwardingServerCall.java
  shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerCallListener.java
  shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java
  shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java
  shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListener.java
Labels: type: refactor, client: spring-mvc, client: spring-cloud

#4467 fix shenyu-sync-data-zookeeper : modify zookeeper sync delete error
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieRuleListener.java
  shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
Labels: type: bug, data-sync: zookeeper

#4446 [type:refactor] refactor rule match cache
  db/init/mysql/schema.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql
  db/upgrade/2.5.1-upgrade-2.6.0-oracle.sql
  db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RuleDTO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorDTO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/RuleDO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/SelectorDO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/RuleVO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/SelectorVO.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/SelectorUtil.java
  shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
  shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-admin/src/main/resources/static/index.2c016d57.js
  shenyu-admin/src/main/resources/static/index.7904889c.css
  shenyu-admin/src/main/resources/static/index.e0e89752.js
  shenyu-admin/src/main/resources/static/index.html
  shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RuleControllerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/SelectorControllerTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/RuleMapperTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/SelectorMapperTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DataPermissionServiceTest.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/RuleData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/SelectorData.java
  shenyu-e2e/pom.xml
  shenyu-e2e/shenyu-e2e-case/src/main/java/org/apache/shenyu/e2e/testcase/common/ResourceDataTemplate.java
  shenyu-e2e/shenyu-e2e-client/src/main/java/org/apache/shenyu/e2e/client/admin/model/data/RuleData.java
  shenyu-e2e/shenyu-e2e-client/src/main/java/org/apache/shenyu/e2e/client/admin/model/data/SelectorData.java
  shenyu-e2e/shenyu-e2e-client/src/test/java/org/apache/shenyu/e2e/client/admin/AdminClientTest.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/AbstractShenyuPluginTest.java
  shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
Labels: type: refactor

#4473 modify pluginJar to Base64 String in PluginData
  shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/PluginTransfer.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
Labels: type: refactor

#4486 [type:fix] fix memory leak
  shenyu-bootstrap/src/main/resources/application.yml
  shenyu-common/src/main/java/org/apache/shenyu/common/cache/WindowTinyLFUMap.java
  shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java
Labels: type: refactor, type: performance

#4488 [ISSUE #4469]add shortestResponseLoadBalancer
  db/init/mysql/schema.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql
  db/upgrade/2.5.1-upgrade-2.6.0-oracle.sql
  db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-common/src/main/java/org/apache/shenyu/common/enums/LoadBalanceEnum.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java
  shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/ShortestResponseLoadBalancer.java
  shenyu-loadbalancer/src/main/resources/META-INF/shenyu/org.apache.shenyu.loadbalancer.spi.LoadBalancer
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/ShortestResponseLoadBalancerTest.java
  shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
  shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/DividePluginTest.java
Labels: type: new feature

#4499 [type:bug] fix bug Query failed because there are too many rules
  shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleConditionMapper.java
  shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
Labels: type: bug, admin

#4383 HashLoadBalancer unit test
  shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalancerTest.java
Labels: in: test

#4501 [type:update] maven-assembly-plugin update version 2.2-beta-5 -> 3.5.0
  pom.xml
  shenyu-dist/shenyu-admin-dist/pom.xml
  shenyu-dist/shenyu-bootstrap-dist/pom.xml
  shenyu-dist/shenyu-docker-compose-dist/pom.xml
  shenyu-dist/shenyu-src-dist/pom.xml
Labels: type: build, type: release

#4503 [type:fix] fix error cache usage
  shenyu-common/src/main/java/org/apache/shenyu/common/cache/WindowTinyLFUMap.java
  shenyu-common/src/test/java/org/apache/shenyu/common/cache/WindowTinyLFUMapTest.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieNode.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java
Labels: plugin: base

#4506 [Fix] missing actuator dependency and port error in examples http
  shenyu-examples/shenyu-examples-http/k8s/shenyu-examples-http-deployment.yml
  shenyu-examples/shenyu-examples-http/pom.xml
Labels: integration-test

#4509 [type:bug] fix bug issue #4487.
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java
Labels: type: bug

#4450 Add unit tests for DetailService.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DetailServiceTest.java
Labels: in: test

#4516 refactor admin : use BearerToken replace StatelessToken for #4496
  shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/bean/StatelessAuthFilter.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/bean/StatelessToken.java
  shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroRealm.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/bean/StatelessTokenTest.java
  shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/config/ShiroRealmTest.java
Labels: type: refactor

#4515 [type:fix] fix trie match error
  shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
  shenyu-bootstrap/src/main/resources/application.yml
  shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
  shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieRuleListener.java
  shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriberTest.java
  shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java
Labels: type: bug, type: refactor
