Repository apache/shenyu, pull requests merged in 2025-01, with the labels that each got.

#5880 [type:fix] exclude shenyu-registry-eureka
  shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/pom.xml
Labels: sdk

#5870 [type:refactor] Optimize code for shenyu-common
  shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeLRUMap.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/AppAuthData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/AuthParamData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/AuthPathData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/ConditionData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/ConfigData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/DiscoveryUpstreamData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/MetaData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/RuleData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/SelectorData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/WebsocketData.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/plugin/DubboRegisterConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/plugin/GrpcRegisterConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/plugin/MotanRegisterConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/plugin/SofaRegisterConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/plugin/TarsRegisterConfig.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/GeneralContextHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/HystrixHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/MockHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/RateLimiterHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/RedirectHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/RequestHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/Resilience4JHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/RewriteHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/SentinelHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/WafHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ContextMappingRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/DivideRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/KeyAuthRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ModifyResponseRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ParamMappingRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/SofaRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/SpringCloudRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/WebSocketRuleHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/CommonUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/DivideUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/GrpcUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/SpringCloudSelectorHandle.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/TarsUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/WebSocketUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/selector/ZombieUpstream.java
  shenyu-common/src/main/java/org/apache/shenyu/common/timer/AbstractRetryTask.java
  shenyu-common/src/main/java/org/apache/shenyu/common/timer/WheelTimerFactory.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/FreshBeanHolder.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/GsonUtils.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/JarDependencyUtils.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/ParamCheckUtils.java
  shenyu-common/src/main/java/org/apache/shenyu/common/utils/VersionUtils.java
Labels: type: refactor

#5871 [type:refactor] Optimize code for shenyu-web
  shenyu-web/src/main/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolver.java
  shenyu-web/src/main/java/org/apache/shenyu/web/loader/PluginJarParser.java
  shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginClassLoader.java
  shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
Labels: type: refactor

#5883 [type:bugfix] fix h2 sql
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
Labels: type: bug, type: fixed

#5889 fixed some bug when using http-polling mode
  shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/DiscoveryUpstreamDataRefresh.java
Labels: type: bug

#5882 [type:refactor] plugin-jwt SPI extension for parsing JWT payloads to ensure compatibility with older versions of JWT tools
  db/init/mysql/schema.sql
  db/init/ob/schema.sql
  db/init/og/create-table.sql
  db/init/oracle/schema.sql
  db/init/pg/create-table.sql
  db/upgrade/2.7.0-upgrade-2.7.1-mysql.sql
  db/upgrade/2.7.0-upgrade-2.7.1-og.sql
  db/upgrade/2.7.0-upgrade-2.7.1-oracle.sql
  db/upgrade/2.7.0-upgrade-2.7.1-pg.sql
  db/upgrade/upgrade-guide.md
  shenyu-admin/src/main/resources/sql-script/h2/schema.sql
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/config/JwtConfig.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandler.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/DefaultJwtPayloadParseStrategy.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/JwtPayloadParseStrategy.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/JwtPayloadParseStrategyFactory.java
  shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.jwt.strategy.JwtPayloadParseStrategy
Labels: type: new feature, plugin: jwt

#5891 [type:fix] support dubbo method configure
  shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
Labels: plugin: dubbo, plugin: apache-dubbo

#5905 [type:optimize] Optimize BodyParamUtils with Caffeine cache
  .gitignore
  shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java
Labels: type: refactor

#5504 fixed RateLimiter remoteAddress issues Please reply #5340.
  shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/resolver/RemoteAddrKeyResolver.java
Labels: type: new feature
